-- =========================================================================
--  IdentiPet — Esquema inicial (Supabase / Postgres)
--  Ejecutar en Supabase: SQL Editor → pegar → Run, o vía CLI `supabase db push`.
-- =========================================================================

create extension if not exists unaccent;

-- ----- Helper: slugify -----
create or replace function public.slugify(v text)
returns text language sql as $$
  select trim(both '-' from regexp_replace(lower(unaccent(coalesce(v, ''))), '[^a-z0-9]+', '-', 'g'));
$$;

-- =========================================================================
--  PERFILES (extiende auth.users)
-- =========================================================================
create table if not exists public.profiles (
  id               uuid primary key references auth.users(id) on delete cascade,
  role             text not null default 'propietario'
                   check (role in ('propietario','veterinario','empresa','administrador')),
  nombre           text not null default '',
  apellido         text not null default '',
  celular          text,
  tipo_documento   text,
  numero_documento text,
  direccion        text,
  distrito         text,
  ciudad           text,
  fecha_nacimiento date,
  avatar_url       text,
  created_at       timestamptz not null default now()
);

-- Crear perfil automáticamente cuando se registra un usuario
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, role, nombre, apellido, celular, tipo_documento, numero_documento)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'role', 'propietario'),
    coalesce(new.raw_user_meta_data->>'nombre', ''),
    coalesce(new.raw_user_meta_data->>'apellido', ''),
    new.raw_user_meta_data->>'celular',
    new.raw_user_meta_data->>'tipo_documento',
    new.raw_user_meta_data->>'numero_documento'
  );
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =========================================================================
--  MASCOTAS
-- =========================================================================
create sequence if not exists public.pet_code_seq;

create table if not exists public.pets (
  id                  bigint generated by default as identity primary key,
  owner_id            uuid not null references public.profiles(id) on delete cascade,
  identipet_code      text unique,
  slug_publico        text unique,
  codigo_interno      text,
  foto_url            text,
  nombre              text not null,
  especie             text not null default 'Perro',
  raza                text,
  sexo                text not null default 'desconocido' check (sexo in ('macho','hembra','desconocido')),
  fecha_nacimiento    date,
  color               text,
  peso                numeric(6,2),
  tiene_microchip     boolean not null default false,
  numero_chip         text,
  caracteristicas     text,
  estado_reproductivo text not null default 'desconocido'
                      check (estado_reproductivo in ('entero','castrado','esterilizado','desconocido')),
  perdido             boolean not null default false,
  perdido_desde       timestamptz,
  recompensa          text,
  estado              text not null default 'activa' check (estado in ('activa','inactiva','fallecida')),
  pago_estado         text not null default 'pendiente' check (pago_estado in ('pendiente','pagado','anulado')),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index if not exists idx_pets_owner on public.pets(owner_id);

-- Generar número IdentiPet, slug y código interno al insertar
create or replace function public.set_pet_identifiers()
returns trigger language plpgsql as $$
declare seqval bigint;
begin
  if new.identipet_code is null then
    seqval := nextval('public.pet_code_seq');
    new.identipet_code := 'IP-' || lpad(seqval::text, 6, '0');
    new.slug_publico := public.slugify(new.nombre) || '-' || seqval::text;
    new.codigo_interno := upper(substr(md5(random()::text), 1, 10));
  end if;
  return new;
end; $$;

drop trigger if exists trg_pet_identifiers on public.pets;
create trigger trg_pet_identifiers
  before insert on public.pets
  for each row execute function public.set_pet_identifiers();

-- =========================================================================
--  CONTACTOS DE EMERGENCIA
-- =========================================================================
create table if not exists public.pet_contacts (
  id           bigint generated by default as identity primary key,
  pet_id       bigint not null references public.pets(id) on delete cascade,
  nombre       text not null,
  telefono     text not null,
  relacion     text,
  es_principal boolean not null default false,
  created_at   timestamptz not null default now()
);
create index if not exists idx_contacts_pet on public.pet_contacts(pet_id);

-- =========================================================================
--  HISTORIAL MÉDICO
-- =========================================================================
create table if not exists public.medical_records (
  id          bigint generated by default as identity primary key,
  pet_id      bigint not null references public.pets(id) on delete cascade,
  vet_id      uuid references public.profiles(id) on delete set null,
  tipo        text not null default 'consulta',
  titulo      text not null,
  descripcion text,
  peso        numeric(6,2),
  archivo_url text,
  fecha       date not null default current_date,
  created_at  timestamptz not null default now()
);
create index if not exists idx_med_pet on public.medical_records(pet_id);

-- =========================================================================
--  VACUNAS
-- =========================================================================
create table if not exists public.vaccines (
  id             bigint generated by default as identity primary key,
  pet_id         bigint not null references public.pets(id) on delete cascade,
  vet_id         uuid references public.profiles(id) on delete set null,
  nombre         text not null,
  lote           text,
  fecha_aplicada date not null,
  proxima_dosis  date,
  archivo_url    text,
  created_at     timestamptz not null default now()
);
create index if not exists idx_vac_pet on public.vaccines(pet_id);

-- =========================================================================
--  DOCUMENTOS
-- =========================================================================
create table if not exists public.documents (
  id         bigint generated by default as identity primary key,
  pet_id     bigint not null references public.pets(id) on delete cascade,
  user_id    uuid references public.profiles(id) on delete set null,
  carpeta    text not null default 'General',
  tipo       text not null default 'otro',
  nombre     text not null,
  ruta_url   text not null,
  mime       text,
  tamano     integer,
  created_at timestamptz not null default now()
);
create index if not exists idx_doc_pet on public.documents(pet_id);

-- =========================================================================
--  RECORDATORIOS
-- =========================================================================
create table if not exists public.reminders (
  id         bigint generated by default as identity primary key,
  pet_id     bigint not null references public.pets(id) on delete cascade,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  tipo       text not null default 'otro',
  titulo     text not null,
  nota       text,
  fecha      timestamptz not null,
  canal      text not null default 'correo',
  enviado    boolean not null default false,
  completado boolean not null default false,
  created_at timestamptz not null default now()
);

-- =========================================================================
--  REGISTROS / PAGOS
-- =========================================================================
create table if not exists public.registrations (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references public.profiles(id) on delete cascade,
  pet_id       bigint not null references public.pets(id) on delete cascade,
  monto        numeric(8,2) not null default 0,
  moneda       text not null default 'PEN',
  metodo       text not null default 'transferencia',
  estado       text not null default 'pendiente' check (estado in ('pendiente','pagado','anulado')),
  referencia   text,
  comprobante_url text,
  created_at   timestamptz not null default now(),
  confirmed_at timestamptz,
  confirmed_by uuid references public.profiles(id)
);
create index if not exists idx_reg_estado on public.registrations(estado);

-- =========================================================================
--  STORAGE: bucket público para fotos de mascotas
-- =========================================================================
insert into storage.buckets (id, name, public)
values ('pets', 'pets', true)
on conflict (id) do nothing;

-- =========================================================================
--  ROW LEVEL SECURITY
-- =========================================================================
alter table public.profiles        enable row level security;
alter table public.pets            enable row level security;
alter table public.pet_contacts    enable row level security;
alter table public.medical_records enable row level security;
alter table public.vaccines        enable row level security;
alter table public.documents       enable row level security;
alter table public.reminders       enable row level security;
alter table public.registrations   enable row level security;

-- Helper: ¿es admin?
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'administrador');
$$;

-- PROFILES: cada quien ve/edita su perfil; admin todo
create policy "perfil propio: leer"   on public.profiles for select using (auth.uid() = id or public.is_admin());
create policy "perfil propio: editar" on public.profiles for update using (auth.uid() = id);

-- PETS: el dueño gestiona las suyas; lectura pública (página por QR); admin todo
create policy "mascotas: lectura pública" on public.pets for select using (true);
create policy "mascotas: dueño inserta"   on public.pets for insert with check (auth.uid() = owner_id);
create policy "mascotas: dueño edita"     on public.pets for update using (auth.uid() = owner_id or public.is_admin());
create policy "mascotas: dueño elimina"   on public.pets for delete using (auth.uid() = owner_id or public.is_admin());

-- CONTACTOS: lectura pública (para mascota perdida); gestiona el dueño de la mascota
create policy "contactos: lectura pública" on public.pet_contacts for select using (true);
create policy "contactos: dueño gestiona"  on public.pet_contacts for all
  using (exists (select 1 from public.pets p where p.id = pet_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from public.pets p where p.id = pet_id and p.owner_id = auth.uid()));

-- HISTORIAL / VACUNAS / DOCUMENTOS: solo el dueño (privado)
create policy "historial: dueño" on public.medical_records for all
  using (exists (select 1 from public.pets p where p.id = pet_id and p.owner_id = auth.uid()) or public.is_admin())
  with check (exists (select 1 from public.pets p where p.id = pet_id and p.owner_id = auth.uid()));
create policy "vacunas: dueño" on public.vaccines for all
  using (exists (select 1 from public.pets p where p.id = pet_id and p.owner_id = auth.uid()) or public.is_admin())
  with check (exists (select 1 from public.pets p where p.id = pet_id and p.owner_id = auth.uid()));
create policy "documentos: dueño" on public.documents for all
  using (exists (select 1 from public.pets p where p.id = pet_id and p.owner_id = auth.uid()) or public.is_admin())
  with check (exists (select 1 from public.pets p where p.id = pet_id and p.owner_id = auth.uid()));

-- RECORDATORIOS: del usuario
create policy "recordatorios: propio" on public.reminders for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- REGISTROS: el usuario ve los suyos; admin gestiona (confirma pagos)
create policy "registros: propio leer" on public.registrations for select using (auth.uid() = user_id or public.is_admin());
create policy "registros: propio crea" on public.registrations for insert with check (auth.uid() = user_id);
create policy "registros: admin edita" on public.registrations for update using (public.is_admin());
